using System.Collections.Generic;
using AngryGuy.Core;
using UnityEngine;

namespace AngryGuy.UnityLayer
{
    /// <summary>
    /// Turns simulation events into sound.
    ///
    /// Audio is doing real work here, not decoration: half of what happens in
    /// this game happens in another room. A crash of breaking crockery or a
    /// distant shout is often the player's only notice that a trap they set two
    /// minutes ago has just gone off.
    ///
    /// Every clip is generated by tools/assets/generate_audio.py.
    /// </summary>
    public sealed class AudioDirector : MonoBehaviour
    {
        private readonly Dictionary<string, AudioClip> _clips = new Dictionary<string, AudioClip>();

        private AudioSource _ui;
        private AudioSource _tension;
        private AudioSource _ambient;

        private Simulation _sim;
        private float _footstepTimer;
        private bool _ready;

        public void Attach(Simulation sim)
        {
            if (!_ready) LoadClips();

            if (_sim != null) _sim.Events.OnEvent -= OnWorldEvent;
            _sim = sim;
            _sim.Events.OnEvent += OnWorldEvent;
        }

        private void OnDestroy()
        {
            if (_sim != null) _sim.Events.OnEvent -= OnWorldEvent;
        }

        private void LoadClips()
        {
            string[] names =
            {
                "footstep", "bell", "clink", "crunch", "splash", "slip", "grumble",
                "shout", "huh", "door", "pickup", "success", "failure",
                "sting_suspicion", "sting_payoff", "blip", "tension_loop", "music_ambient",
                "voice_gruff_short", "voice_gruff_mid", "voice_gruff_long",
                "voice_bright_short", "voice_bright_mid", "voice_bright_long",
                "voice_soft_short", "voice_soft_mid", "voice_soft_long",
                "voice_crisp_short", "voice_crisp_mid", "voice_crisp_long",
                "voice_flat_short", "voice_flat_mid", "voice_flat_long",
                "voice_reedy_short", "voice_reedy_mid", "voice_reedy_long",
                "repair", "clatter"
            };

            for (int i = 0; i < names.Length; i++)
            {
                AudioClip clip = Resources.Load<AudioClip>("Audio/" + names[i]);
                if (clip != null) _clips[names[i]] = clip;
            }

            _ui = gameObject.AddComponent<AudioSource>();
            _ui.spatialBlend = 0f;
            _ui.playOnAwake = false;

            _ambient = gameObject.AddComponent<AudioSource>();
            _ambient.spatialBlend = 0f;
            _ambient.playOnAwake = false;
            _ambient.loop = true;
            _ambient.volume = 0.22f;
            if (_clips.ContainsKey("music_ambient"))
            {
                _ambient.clip = _clips["music_ambient"];
                _ambient.Play();
            }

            _tension = gameObject.AddComponent<AudioSource>();
            _tension.spatialBlend = 0f;
            _tension.playOnAwake = false;
            _tension.loop = true;
            _tension.volume = 0f;
            if (_clips.ContainsKey("tension_loop"))
            {
                _tension.clip = _clips["tension_loop"];
                _tension.Play();
            }

            _ready = true;
        }

        // ------------------------------------------------------------------

        private void OnWorldEvent(WorldEvent e)
        {
            switch (e.Kind)
            {
                case EventKind.ObjectBroken:
                    At("crunch", e.Position, 0.9f);
                    break;

                case EventKind.SpillCreated:
                    At("splash", e.Position, 0.8f);
                    break;

                case EventKind.Slipped:
                    At("slip", e.Position, 1f);
                    break;

                case EventKind.FoodRuined:
                    At("crunch", e.Position, 0.7f);
                    break;

                case EventKind.PlanFailed:
                    At("grumble", e.Position, 0.8f);
                    break;

                case EventKind.Discovery:
                    At("huh", e.Position, 0.7f);
                    break;

                case EventKind.Accusation:
                case EventKind.Argument:
                    At("shout", e.Position, 0.75f);
                    break;

                case EventKind.Outburst:
                    At("shout", e.Position, 1f);
                    break;

                case EventKind.ObjectTaken:
                case EventKind.ObjectTampered:
                    // A clumsy NPC knocking something over is loud and obviously
                    // an accident; the player quietly pocketing it is not.
                    if (e.Loudness > 0.35f) At("clatter", e.Position, 0.75f);
                    else At("pickup", e.Position, 0.5f);
                    break;

                case EventKind.Noise:
                    // The sound of your sabotage being undone in the next room.
                    if (e.Description.Contains("sorts out")) At("repair", e.Position, 0.7f);
                    else if (e.ObjectId == "bell") At("bell", e.Position, 0.9f);
                    else if (e.ObjectId == "door") At("door", e.Position, 0.7f);
                    else if (e.Loudness > 0.5f) At("clink", e.Position, 0.85f);
                    break;
            }
        }

        /// <summary>UI-side reactions to feedback the player is meant to notice.</summary>
        public void OnFeedback(FeedbackEvent feedback)
        {
            switch (feedback.Kind)
            {
                case FeedbackKind.Alert:
                    Ui("sting_suspicion", 0.6f);
                    break;
                case FeedbackKind.Payoff:
                    Ui("sting_payoff", 0.6f);
                    break;
                case FeedbackKind.Objective:
                    Ui("success", 0.5f);
                    break;
            }
        }

        public void OnOutcome(GameOutcome outcome)
        {
            if (outcome == GameOutcome.Won) Ui("success", 0.8f);
            else if (outcome != GameOutcome.InProgress) Ui("failure", 0.7f);
        }

        public void TickPlayer(bool moving, bool sneaking, float dt, Vector3 position)
        {
            if (!_ready) return;

            if (!moving)
            {
                _footstepTimer = 0f;
                return;
            }

            _footstepTimer -= dt;
            if (_footstepTimer > 0f) return;

            _footstepTimer = sneaking ? 0.62f : 0.38f;
            At("footstep", LevelView.ToSim(position), sneaking ? 0.18f : 0.45f);
        }

        /// <summary>Music bed rises with whoever is most suspicious of the player.</summary>
        public void TickTension(float highestSuspicion, float dt)
        {
            if (_tension == null) return;
            float target = Mathf.Clamp01(highestSuspicion) * 0.45f;
            _tension.volume = Mathf.MoveTowards(_tension.volume, target, dt * 0.35f);
        }

        /// <summary>
        /// Give an NPC a voice. Four profiles keyed off the character, three
        /// lengths keyed off how much they just said - enough that you can tell
        /// who is shouting in the next room without looking.
        /// </summary>
        public void Speak(Npc npc, string line)
        {
            if (line.Length == 0) return;

            string profile = VoiceProfileFor(npc);

            string length = "short";
            if (line.Length > 18) length = "mid";
            if (line.Length > 34 || line.ToUpperInvariant() == line) length = "long";

            float volume = length == "long" ? 0.85f : 0.55f;
            At("voice_" + profile + "_" + length, LevelView.ToSim(LevelView.ToUnity(npc.Position)), volume);
        }

        private static string VoiceProfileFor(Npc npc)
        {
            switch (npc.Role)
            {
                case "head chef": return "gruff";
                case "waiter": return "bright";
                case "dishwasher": return "soft";
                case "sous chef": return "flat";
                case "kitchen porter": return "reedy";
                default: return "crisp";
            }
        }

        // ------------------------------------------------------------------

        private void At(string clipName, Vec3 position, float volume)
        {
            AudioClip clip;
            if (!_clips.TryGetValue(clipName, out clip) || clip == null) return;
            AudioSource.PlayClipAtPoint(clip, LevelView.ToUnity(position), volume);
        }

        private void Ui(string clipName, float volume)
        {
            AudioClip clip;
            if (_ui == null || !_clips.TryGetValue(clipName, out clip) || clip == null) return;
            _ui.PlayOneShot(clip, volume);
        }
    }
}
